apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcpdevops-deployment
  namespace: cluster-1  # Namespace updated to cluster-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcpdevops
  template:
    metadata:
      labels:
        app: gcpdevops
    spec:
      containers:
      - name: gcpdevops-container
        image: gcr.io/$PROJECT_ID/gcpdevops  # Ensure the correct image path
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gcpdevops-service
  namespace: cluster-1  # Namespace updated to cluster-1
spec:
  selector:
    app: gcpdevops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
